[package]
name = "wll"
version = "0.1.0"
authors = ["miroox <miroox@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "sys",
    "macros",
]

[dependencies]
wll-sys = { version = "0.1", path = "sys" }
