//! `wll-sys` is a low-level bindings for Wolfram LibraryLink.
//! Typically doesn’t need to be used directly.
//!
//! It is automatically generated by [bindgen](https://crates.io/crates/bindgen).
//!
//! **see also**: [Wolfram LibraryLink User Guide], [LibraryLink Reference].
//!
//! [Wolfram LibraryLink User Guide]: http://reference.wolfram.com/language/LibraryLink/tutorial/Overview.html
//! [LibraryLink Reference]: http://reference.wolfram.com/language/LibraryLink/tutorial/Reference.html

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

mod global;
mod numeric_array;
mod raw_array;
mod sparse;

//pub use global::*;

mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::*;

pub const True: mbool = bindings::True as mbool;
pub const False: mbool = bindings::False as mbool;
pub const WolframLibraryVersion: mint = bindings::WolframLibraryVersion as mint;
pub const LIBRARY_NO_ERROR: errcode_t = bindings::LIBRARY_NO_ERROR as errcode_t;
pub const LIBRARY_TYPE_ERROR: errcode_t = bindings::LIBRARY_TYPE_ERROR as errcode_t;
pub const LIBRARY_RANK_ERROR: errcode_t = bindings::LIBRARY_RANK_ERROR as errcode_t;
pub const LIBRARY_DIMENSION_ERROR: errcode_t = bindings::LIBRARY_DIMENSION_ERROR as errcode_t;
pub const LIBRARY_NUMERICAL_ERROR: errcode_t = bindings::LIBRARY_NUMERICAL_ERROR as errcode_t;
pub const LIBRARY_MEMORY_ERROR: errcode_t = bindings::LIBRARY_MEMORY_ERROR as errcode_t;
pub const LIBRARY_FUNCTION_ERROR: errcode_t = bindings::LIBRARY_FUNCTION_ERROR as errcode_t;
pub const LIBRARY_VERSION_ERROR: errcode_t = bindings::LIBRARY_VERSION_ERROR as errcode_t;
