//! # wll-sys
//!
//! `wll-sys` is a low-level bindings for Wolfram LibraryLink.
//! Typically doesn’t need to be used directly.
//!
//! It is automatically generated by [bindgen](https://crates.io/crates/bindgen).
//!
//! **see also**: [Wolfram LibraryLink User Guide](http://reference.wolfram.com/language/LibraryLink/tutorial/Overview.html).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

pub const TRUE: mbool = True as mbool;
pub const FALSE: mbool = False as mbool;
