[package]
name = "wll-macros"
version = "0.1.0"
authors = ["miroox <miroox@outlook.com>"]
edition = "2018"

[lib]
proc-macro=true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
