[package]
name = "basic"
version = "0.1.0"
authors = ["miroox <miroox@outlook.com>"]
edition = "2018"
publish = false

[lib]
crate-type = [ "cdylib" ]

[features]
auto-link = ["wll/auto-link"]

[dependencies]
wll = { path = "../..", features = ["macros"] }
