name: CI

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest
          - name: Ubuntu
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Install LLVM for Windows
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: .\.github\workflows\intall-llvm.ps1
        shell: powershell
      - name: Build
        run: cargo build --all --verbose
      - name: Test
        run: cargo test --all --verbose
